---
# Source: templates/configmap-observability.yaml
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: observability-dev-config 
  labels:
    app: observability
data: 
    app.yaml: "#KubeArmor Config\nkubeArmor:\n  url: 127.0.0.1\n  port: 32766\n\n#Cilium Config\ncilium:\n  url: 127.0.0.1\n  port: 4245\n  \nlogging:\n  level: \"INFO\""
---
# Source: templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: observability
  labels:
    app: observability
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP
      name: http
  selector:
    app: observability
---
# Source: templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability
  labels:
    app: observability    
spec:
  selector:
    matchLabels:
        app: observability
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: observability        
    spec:
      serviceAccountName: 
      securityContext:
        
        fsGroup: 1337
      volumes:
        
        null
      containers:
      - name: observability
        image: 'gcr.io/mimetic-kit-294408/development/observability:1.16.0'
        imagePullPolicy: Always
        volumeMounts:
          
            null
        resources:
          
            limits:
              cpu: 0.6
              memory: 900M
            requests:
              cpu: 0.4
              memory: 800M
        ports:
          
            - containerPort: 8089
---
# Source: templates/hpa.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: observability
  labels:
    app: observability
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: observability
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
