apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: observability
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: observability
  namespace: kube-system
spec:
  selector:
    observability-app: observability
  type: LoadBalancer
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089