// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package aggregator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AggregatorClient is the client API for Aggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregatorClient interface {
	FetchNetworkLogs(ctx context.Context, in *NetworkLogsRequest, opts ...grpc.CallOption) (*NetworkLogsResponse, error)
	FetchSystemLogs(ctx context.Context, in *SystemLogsRequest, opts ...grpc.CallOption) (*SystemLogsResponse, error)
}

type aggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregatorClient(cc grpc.ClientConnInterface) AggregatorClient {
	return &aggregatorClient{cc}
}

func (c *aggregatorClient) FetchNetworkLogs(ctx context.Context, in *NetworkLogsRequest, opts ...grpc.CallOption) (*NetworkLogsResponse, error) {
	out := new(NetworkLogsResponse)
	err := c.cc.Invoke(ctx, "/aggregator.Aggregator/FetchNetworkLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorClient) FetchSystemLogs(ctx context.Context, in *SystemLogsRequest, opts ...grpc.CallOption) (*SystemLogsResponse, error) {
	out := new(SystemLogsResponse)
	err := c.cc.Invoke(ctx, "/aggregator.Aggregator/FetchSystemLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregatorServer is the server API for Aggregator service.
// All implementations must embed UnimplementedAggregatorServer
// for forward compatibility
type AggregatorServer interface {
	FetchNetworkLogs(context.Context, *NetworkLogsRequest) (*NetworkLogsResponse, error)
	FetchSystemLogs(context.Context, *SystemLogsRequest) (*SystemLogsResponse, error)
	mustEmbedUnimplementedAggregatorServer()
}

// UnimplementedAggregatorServer must be embedded to have forward compatible implementations.
type UnimplementedAggregatorServer struct {
}

func (UnimplementedAggregatorServer) FetchNetworkLogs(context.Context, *NetworkLogsRequest) (*NetworkLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchNetworkLogs not implemented")
}
func (UnimplementedAggregatorServer) FetchSystemLogs(context.Context, *SystemLogsRequest) (*SystemLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSystemLogs not implemented")
}
func (UnimplementedAggregatorServer) mustEmbedUnimplementedAggregatorServer() {}

// UnsafeAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregatorServer will
// result in compilation errors.
type UnsafeAggregatorServer interface {
	mustEmbedUnimplementedAggregatorServer()
}

func RegisterAggregatorServer(s grpc.ServiceRegistrar, srv AggregatorServer) {
	s.RegisterService(&Aggregator_ServiceDesc, srv)
}

func _Aggregator_FetchNetworkLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServer).FetchNetworkLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aggregator.Aggregator/FetchNetworkLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServer).FetchNetworkLogs(ctx, req.(*NetworkLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aggregator_FetchSystemLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServer).FetchSystemLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aggregator.Aggregator/FetchSystemLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServer).FetchSystemLogs(ctx, req.(*SystemLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Aggregator_ServiceDesc is the grpc.ServiceDesc for Aggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aggregator.Aggregator",
	HandlerType: (*AggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchNetworkLogs",
			Handler:    _Aggregator_FetchNetworkLogs_Handler,
		},
		{
			MethodName: "FetchSystemLogs",
			Handler:    _Aggregator_FetchSystemLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/aggregator/aggregator.proto",
}
